package org.baxter_academy.caal_g3;

import android.app.Service;
import android.content.Context;
import android.content.Intent;
import android.os.IBinder;
import android.support.annotation.Nullable;
import android.support.v4.content.LocalBroadcastManager;
import android.util.Log;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;

import weka.classifiers.Classifier;
import weka.core.Instances;

//TODO add broadcast for finishing of work
public class WekaClassifier extends Service {

    @Override
    public void onCreate() {
        System.out.println("Started WekaClassifier");
        super.onCreate();

        /** ASSIGN / LOAD RESOURCES **/
        // assigns classifier
        InputStream classifier = getResources().openRawResource(R.raw.randomforestbinarycfscsc20);

        Classifier cls = null; // TODO study SerializationHelper
        try {
            cls = (Classifier) weka.core.SerializationHelper.read(classifier);
        } catch (Exception e) {
            e.printStackTrace();
        }


        // assigns/loads data from raw resources (prepackaged)
         Reader reader = new InputStreamReader(
         getResources().openRawResource(R.raw.testunlabeledbinarycfs)
         );
         // load unlabeled data
         Instances unlabeled = null;
         try {
         unlabeled = new Instances(
         new BufferedReader(reader));
         } catch (IOException e) {
         e.printStackTrace();
         }

//TODO load data from local storage instead of resources
/** NOT WORKING updated code to assign / load data from local storage (generated by cleaner)
        // assign unlabeled data
        File path = getBaseContext().getFilesDir();
        File unlabeledDataFile = new File(path, "unlabeledData");
        int length = (int) unlabeledDataFile.length();

        byte[] bytes = new byte[length];

        FileInputStream in = null;
        try {
            in = new FileInputStream(unlabeledDataFile);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        try {
            in.read(bytes);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                in.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        String contents = new String(bytes);

        // load unlabeled data
        Instances unlabeled = null;
        try {
            unlabeled = new Instances(new InputStreamReader(new FileInputStream(unlabeledDataFile)));
        } catch (IOException e) {
            e.printStackTrace();
        }
**/

        /** PREPARE OPERATIONS **/
        // set class attribute
        unlabeled.setClassIndex(unlabeled.numAttributes() - 1);

        // create copy
        Instances labeled = new Instances(unlabeled);

        /** PERFORM CLASSIFICATION **/
        // label instances
        for (int i = 0; i < unlabeled.numInstances(); i++) {
            double clsLabel = 0;
            try {
                clsLabel = cls.classifyInstance(unlabeled.instance(i));
            } catch (Exception e) {
                e.printStackTrace();
            }
            labeled.instance(i).setClassValue(clsLabel);
        }

        /** SAVE LABELED INSTANCE **/
        String FILENAME = "classification";
        BufferedWriter writer = null;

        // opens file for writing
        try {
            writer = new BufferedWriter(
                    new FileWriter(new File(getFilesDir(), FILENAME)
                    ));

        } catch (IOException e) {
            e.printStackTrace();
        }

        // writes to file
        String toWrite = labeled.toString();
        try {
            System.out.println(labeled); // debug
            if (writer != null) {
                writer.write(toWrite);
                writer.newLine();
                writer.flush();
                writer.close();
                System.out.println("file reference is not null");
            } else {
                System.out.println("file reference is null");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        /** FINISH **/
        stopSelf();
    }

    public void onDestroy() {
        System.out.println("Stopped WekaClassifier");
        Log.d("sender", "Broadcasting message");
        Intent intent = new Intent("FinishedWork");

        intent.putExtra("status", "WekaClassifier finished");
        LocalBroadcastManager.getInstance(this).sendBroadcast(intent);
    }

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }
}